// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFmhaIHmq5iD_fOUaXYhByhH_0A7WdNVA',
    appId: '1:867191951234:web:cdf21b4360005e2e03c99b',
    messagingSenderId: '867191951234',
    projectId: 'heresy-unbound',
    authDomain: 'heresy-unbound.firebaseapp.com',
    storageBucket: 'heresy-unbound.firebasestorage.app',
    measurementId: 'G-TJ696ZXWKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmOjK1PgXjppZt_x0QbDpT2v8PGQQv168',
    appId: '1:867191951234:android:6c775d5b830e175003c99b',
    messagingSenderId: '867191951234',
    projectId: 'heresy-unbound',
    storageBucket: 'heresy-unbound.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMfAMal6XbRJKpg-gIwry_D05QMWcgtiA',
    appId: '1:867191951234:ios:c22fb2933db001a803c99b',
    messagingSenderId: '867191951234',
    projectId: 'heresy-unbound',
    storageBucket: 'heresy-unbound.firebasestorage.app',
    iosBundleId: 'com.example.fansiteWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMfAMal6XbRJKpg-gIwry_D05QMWcgtiA',
    appId: '1:867191951234:ios:c22fb2933db001a803c99b',
    messagingSenderId: '867191951234',
    projectId: 'heresy-unbound',
    storageBucket: 'heresy-unbound.firebasestorage.app',
    iosBundleId: 'com.example.fansiteWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFmhaIHmq5iD_fOUaXYhByhH_0A7WdNVA',
    appId: '1:867191951234:web:eda5f74c7289d06f03c99b',
    messagingSenderId: '867191951234',
    projectId: 'heresy-unbound',
    authDomain: 'heresy-unbound.firebaseapp.com',
    storageBucket: 'heresy-unbound.firebasestorage.app',
    measurementId: 'G-PG9ZH0WQ1W',
  );
}
